// GENERATED by tool/generate_event_registry.mjs; do not edit.
export const registryVersion = 1;
export const eventRegistry = {
  "analytics_consent": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "landing_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "invite_link_open": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "download_click": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "store_page_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "installer_started": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "install_completed": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "first_launch": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      },
      "measurementSource": {
        "enum": [
          "website_receipt",
          "installer_receipt"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_provider_selected": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_succeeded": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": true
  },
  "signin_failed": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "reason": {
        "enum": [
          "cancelled",
          "network",
          "provider",
          "invalid_token",
          "configuration",
          "unknown"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "aspiration_selected": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "recipe_created": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "templateCategory": {
        "enum": [
          "calm",
          "focus",
          "health",
          "learning",
          "connection"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "celebration_practiced": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "first_checkin": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "result": {
        "enum": [
          "did",
          "didMore",
          "notToday",
          "undo"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "checkin": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "result": {
        "enum": [
          "did",
          "didMore",
          "notToday",
          "undo"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "comeback": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "recipe_doctor_applied": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "automaticity_score": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "reflection": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "weekly_reflection": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "habit_graduated": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "share_initiated": {
    "properties": {
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "invite_accepted": {
    "properties": {
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "buddy_added": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "paywall_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "trial_start": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "purchase": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "feedback_submitted": {
    "properties": {
      "feedbackId": {
        "type": "uuid"
      },
      "kind": {
        "enum": [
          "Idea",
          "Bug",
          "Question",
          "Praise",
          "This felt wrong",
          "Rating"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "rating_prompted": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": true
  },
  "rating_prompt_shown": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "rated": {
    "properties": {
      "rating": {
        "type": "integer",
        "min": 1,
        "max": 5
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "review_responded": {
    "properties": {
      "feedbackId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "reminder_sent": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "notif_sent": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_delivered": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_opened": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_actioned": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "action": {
        "enum": [
          "did",
          "snooze",
          "fewer",
          "off",
          "open"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_dismissed": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_disabled": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "reminder_preference_started": {
    "properties": {
      "disclosureVersion": {
        "type": "integer",
        "min": 1,
        "max": 1
      },
      "cohortId": {
        "type": "uuid"
      },
      "consentEpoch": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false,
    "required": [
      "disclosureVersion",
      "cohortId",
      "consentEpoch",
      "platform",
      "localDay"
    ]
  },
  "reminder_preference_disabled": {
    "properties": {
      "disclosureVersion": {
        "type": "integer",
        "min": 1,
        "max": 1
      },
      "cohortId": {
        "type": "uuid"
      },
      "consentEpoch": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false,
    "required": [
      "disclosureVersion",
      "cohortId",
      "consentEpoch",
      "platform",
      "localDay"
    ]
  },
  "reminder_preference_followup": {
    "properties": {
      "disclosureVersion": {
        "type": "integer",
        "min": 1,
        "max": 1
      },
      "cohortId": {
        "type": "uuid"
      },
      "consentEpoch": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false,
    "required": [
      "disclosureVersion",
      "cohortId",
      "consentEpoch",
      "platform",
      "localDay"
    ]
  },
  "session_started": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "crash": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      },
      "diagnosticSource": {
        "enum": [
          "flutter_framework",
          "dart_unhandled"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "app_hang": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      }
    },
    "observable": true,
    "legacy": false
  },
  "cold_start": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      }
    },
    "observable": true,
    "legacy": false
  },
  "sync_error": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "auth_error": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "experiment_exposure": {
    "properties": {
      "experiment": {
        "enum": [
          "reminder_copy_v1"
        ]
      },
      "variant": {
        "enum": [
          "control",
          "gentle"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  }
};
export const eventJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Bloomstep telemetry v1",
  "oneOf": [
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "analytics_consent"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "landing_view"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "invite_link_open"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "download_click"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "store_page_view"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "installer_started"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "install_completed"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "first_launch"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "signin_view"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "measurementSource": {
              "type": "string",
              "enum": [
                "website_receipt",
                "installer_receipt"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "signin_provider_selected"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "provider": {
              "type": "string",
              "enum": [
                "email",
                "google",
                "microsoft"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "sessionId": {
              "type": "string",
              "format": "uuid"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "signin_succeeded"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "provider": {
              "type": "string",
              "enum": [
                "email",
                "google",
                "microsoft"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "signin_failed"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "provider": {
              "type": "string",
              "enum": [
                "email",
                "google",
                "microsoft"
              ]
            },
            "reason": {
              "type": "string",
              "enum": [
                "cancelled",
                "network",
                "provider",
                "invalid_token",
                "configuration",
                "unknown"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "sessionId": {
              "type": "string",
              "format": "uuid"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "aspiration_selected"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "recipe_created"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "templateCategory": {
              "type": "string",
              "enum": [
                "calm",
                "focus",
                "health",
                "learning",
                "connection"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "celebration_practiced"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "first_checkin"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "result": {
              "type": "string",
              "enum": [
                "did",
                "didMore",
                "notToday",
                "undo"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "checkin"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "result": {
              "type": "string",
              "enum": [
                "did",
                "didMore",
                "notToday",
                "undo"
              ]
            },
            "latencyMs": {
              "type": "number",
              "minimum": 0,
              "maximum": 86400000
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "comeback"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "recipe_doctor_applied"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "automaticity_score"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "score": {
              "type": "number",
              "minimum": 1,
              "maximum": 7
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "reflection"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "score": {
              "type": "number",
              "minimum": 1,
              "maximum": 7
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "weekly_reflection"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "habit_graduated"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "score": {
              "type": "number",
              "minimum": 1,
              "maximum": 7
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "share_initiated"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "invite_accepted"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "channel": {
              "type": "string",
              "enum": [
                "website",
                "invite",
                "store",
                "direct",
                "unknown",
                "link",
                "email"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "buddy_added"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "paywall_view"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "trial_start"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "purchase"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "feedback_submitted"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "feedbackId": {
              "type": "string",
              "format": "uuid"
            },
            "kind": {
              "type": "string",
              "enum": [
                "Idea",
                "Bug",
                "Question",
                "Praise",
                "This felt wrong",
                "Rating"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "rating_prompted"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "rating_prompt_shown"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "rated"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "rating": {
              "type": "integer",
              "minimum": 1,
              "maximum": 5
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "review_responded"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "feedbackId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "reminder_sent"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_sent"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "habitId": {
              "type": "string",
              "format": "uuid"
            },
            "localDay": {
              "type": "string",
              "format": "date"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_delivered"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_opened"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_actioned"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "action": {
              "type": "string",
              "enum": [
                "did",
                "snooze",
                "fewer",
                "off",
                "open"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_dismissed"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "notificationId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "notif_disabled"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "reminder_preference_started"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "disclosureVersion",
            "cohortId",
            "consentEpoch",
            "platform",
            "localDay"
          ],
          "properties": {
            "disclosureVersion": {
              "type": "integer",
              "minimum": 1,
              "maximum": 1
            },
            "cohortId": {
              "type": "string",
              "format": "uuid"
            },
            "consentEpoch": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "reminder_preference_disabled"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "disclosureVersion",
            "cohortId",
            "consentEpoch",
            "platform",
            "localDay"
          ],
          "properties": {
            "disclosureVersion": {
              "type": "integer",
              "minimum": 1,
              "maximum": 1
            },
            "cohortId": {
              "type": "string",
              "format": "uuid"
            },
            "consentEpoch": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "reminder_preference_followup"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "disclosureVersion",
            "cohortId",
            "consentEpoch",
            "platform",
            "localDay"
          ],
          "properties": {
            "disclosureVersion": {
              "type": "integer",
              "minimum": 1,
              "maximum": 1
            },
            "cohortId": {
              "type": "string",
              "format": "uuid"
            },
            "consentEpoch": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows"
              ]
            },
            "localDay": {
              "type": "string",
              "format": "date"
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "session_started"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "crash"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "errorKind": {
              "type": "string",
              "enum": [
                "network",
                "authentication",
                "conflict",
                "quota",
                "validation",
                "unavailable",
                "unknown"
              ]
            },
            "diagnosticSource": {
              "type": "string",
              "enum": [
                "flutter_framework",
                "dart_unhandled"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "app_hang"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "latencyMs": {
              "type": "number",
              "minimum": 0,
              "maximum": 86400000
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "cold_start"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "sessionId": {
              "type": "string",
              "format": "uuid"
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "latencyMs": {
              "type": "number",
              "minimum": 0,
              "maximum": 86400000
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "sync_error"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "errorKind": {
              "type": "string",
              "enum": [
                "network",
                "authentication",
                "conflict",
                "quota",
                "validation",
                "unavailable",
                "unknown"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "auth_error"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            },
            "errorKind": {
              "type": "string",
              "enum": [
                "network",
                "authentication",
                "conflict",
                "quota",
                "validation",
                "unavailable",
                "unknown"
              ]
            }
          }
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "ts"
      ],
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "const": "experiment_exposure"
        },
        "ts": {
          "type": "string",
          "format": "date-time",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$"
        },
        "schemaVersion": {
          "const": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "experiment": {
              "type": "string",
              "enum": [
                "reminder_copy_v1"
              ]
            },
            "variant": {
              "type": "string",
              "enum": [
                "control",
                "gentle"
              ]
            },
            "platform": {
              "type": "string",
              "enum": [
                "windows",
                "macos",
                "linux",
                "android",
                "ios",
                "web"
              ]
            }
          }
        }
      }
    }
  ]
};
