import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const source = JSON.parse(await readFile(new URL('shared/event-registry.json', root), 'utf8'));
if (!Number.isInteger(source.version) || source.version < 1) throw new Error('Invalid registry version');
for (const [key, rule] of Object.entries(source.definitions)) {
  if (!/^[a-zA-Z][a-zA-Z0-9]*$/.test(key)) throw new Error(`Invalid property ${key}`);
  if (rule.enum) {
    if (Object.keys(rule).length !== 1 || !Array.isArray(rule.enum) || !rule.enum.length
      || rule.enum.some(value => typeof value !== 'string' || value.length > 40) || new Set(rule.enum).size !== rule.enum.length) throw new Error(`Invalid enum ${key}`);
  } else if (!['uuid','date','number','integer'].includes(rule.type)
    || Object.keys(rule).some(field => !['type','min','max'].includes(field))
    || ['number','integer'].includes(rule.type) && (!Number.isFinite(rule.min) || !Number.isFinite(rule.max) || rule.min > rule.max)) throw new Error(`Invalid rule ${key}`);
}
const registry = Object.fromEntries(Object.entries(source.events).map(([name, entry]) => {
  if (!/^[a-z][a-z0-9_]+$/.test(name) || !Array.isArray(entry.properties)
    || new Set(entry.properties).size !== entry.properties.length
    || Object.keys(entry).some(key => !['properties','observable','legacy','required','fixed'].includes(key))
    || entry.required !== undefined && (!Array.isArray(entry.required) ||
      new Set(entry.required).size !== entry.required.length || entry.required.some(key => !entry.properties.includes(key)))) throw new Error(`Invalid event ${name}`);
  const properties = Object.fromEntries(entry.properties.map(key => {
    if (!source.definitions[key]) throw new Error(`Unknown property ${key}`);
    return [key, source.definitions[key]];
  }));
  if (entry.fixed !== undefined) {
    if (entry.fixed === null || typeof entry.fixed !== 'object' || Array.isArray(entry.fixed)) throw new Error(`Invalid fixed properties ${name}`);
    for (const [key, value] of Object.entries(entry.fixed)) {
      if (!properties[key]?.enum?.includes(value)) throw new Error(`Invalid fixed property ${name}.${key}`);
      properties[key] = { enum: [value] };
    }
  }
  return [name, { properties, observable: entry.observable !== false, legacy: entry.legacy === true,
    ...(entry.required ? { required: entry.required } : {}) }];
}));
const json = JSON.stringify(registry, null, 2);
const ruleSchema = rule => rule.enum ? { type: 'string', enum: rule.enum }
  : rule.type === 'uuid' || rule.type === 'date' ? { type: 'string', format: rule.type }
    : { type: rule.type, minimum: rule.min, maximum: rule.max };
const schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema', title: `Bloomstep telemetry v${source.version}`,
  oneOf: Object.entries(registry).map(([name, entry]) => ({
    type: 'object', additionalProperties: false, required: ['id','name','ts', ...(entry.required?.length ? ['properties'] : [])],
    properties: {
      id: { type: 'string', format: 'uuid' }, name: { const: name },
      ts: { type: 'string', format: 'date-time', pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$' },
      schemaVersion: { const: source.version },
      properties: { type: 'object', additionalProperties: false, ...(entry.required ? { required: entry.required } : {}),
        properties: Object.fromEntries(Object.entries(entry.properties).map(([key, rule]) => [key, ruleSchema(rule)])) },
    },
  })),
};
const js = `// GENERATED by tool/generate_event_registry.mjs; do not edit.\nexport const registryVersion = ${source.version};\nexport const eventRegistry = ${json};\nexport const eventJsonSchema = ${JSON.stringify(schema, null, 2)};\n`;
const propertyType = rule => rule.enum ? rule.enum.map(value => JSON.stringify(value)).join(' | ') : ['uuid','date'].includes(rule.type) ? 'string' : 'number';
const types = `// GENERATED by tool/generate_event_registry.mjs; do not edit.
export declare const registryVersion: ${source.version};
export type EventName = ${Object.keys(registry).map(name => JSON.stringify(name)).join(' | ')};
export type PropertyRule = { enum: string[] } | { type: "uuid" | "date" } | { type: "number" | "integer", min: number, max: number };
export declare const eventRegistry: Record<EventName, { properties: Record<string, PropertyRule>, observable: boolean, legacy: boolean, required?: string[] }>;
export declare const eventJsonSchema: Record<string, unknown>;
export type TelemetryEvent = ${Object.entries(registry).map(([name, entry]) => `{ id: string; name: ${JSON.stringify(name)}; ts: string; schemaVersion?: ${source.version}; properties${entry.required?.length ? '' : '?'}: { ${Object.entries(entry.properties).map(([key, rule]) => `${key}${entry.required?.includes(key) ? '' : '?'}: ${propertyType(rule)}`).join('; ')} } }`).join('\n  | ')};
`;
const dart = `// GENERATED by tool/generate_event_registry.mjs; do not edit.
import 'dart:convert';

const eventRegistryVersion = ${source.version};
const eventNames = <String>{${Object.keys(registry).map(name => `'${name}'`).join(',')}};
final Map<String, dynamic> eventRegistry = jsonDecode(r'''${json}''') as Map<String, dynamic>;

bool isValidEventProperties(String name, Map<String, Object?> properties) {
  final entry = eventRegistry[name];
  if (entry == null) return false;
  final rules = entry['properties'] as Map<String, dynamic>;
  final required = entry['required'] as List? ?? [];
  if (required.any((key) => !properties.containsKey(key))) return false;
  for (final property in properties.entries) {
    final rule = rules[property.key];
    final value = property.value;
    if (rule == null) return false;
    if (rule['enum'] != null) {
      if (value is! String || !(rule['enum'] as List).contains(value)) return false;
    } else if (rule['type'] == 'uuid') {
      if (value is! String || !RegExp(r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$').hasMatch(value)) return false;
    } else if (rule['type'] == 'date') {
      if (value is! String || !RegExp(r'^\\d{4}-\\d{2}-\\d{2}$').hasMatch(value)) return false;
      final date = DateTime.tryParse('\${value}T00:00:00Z');
      if (date == null || date.toIso8601String().substring(0, 10) != value) return false;
    } else {
      if (value is! num || !value.isFinite || value < (rule['min'] as num) || value > (rule['max'] as num)) return false;
      if (rule['type'] == 'integer' && value != value.truncateToDouble()) return false;
    }
  }
  return true;
}
`;
for (const [path, content] of [['api/src/event_registry.g.mjs', js], ['api/src/event_registry.g.d.mts', types], ['lib/core/event_registry.g.dart', dart]]) {
  const url = new URL(path, root);
  if (process.argv.includes('--check')) {
    if (await readFile(url, 'utf8') !== content) throw new Error(`Generated registry drift: ${path}`);
  } else await writeFile(url, content);
}
