// GENERATED by tool/generate_event_registry.mjs; do not edit.
import 'dart:convert';

const eventRegistryVersion = 1;
const eventNames = <String>{'analytics_consent','landing_view','invite_link_open','download_click','store_page_view','installer_started','install_completed','first_launch','signin_view','signin_provider_selected','signin_succeeded','signin_failed','aspiration_selected','recipe_created','celebration_practiced','first_checkin','checkin','comeback','recipe_doctor_applied','automaticity_score','reflection','weekly_reflection','habit_graduated','share_initiated','invite_accepted','buddy_added','paywall_view','trial_start','purchase','feedback_submitted','rating_prompted','rating_prompt_shown','rated','review_responded','reminder_sent','notif_sent','notif_delivered','notif_opened','notif_actioned','notif_dismissed','notif_disabled','session_started','crash','app_hang','cold_start','sync_error','auth_error','experiment_exposure'};
final Map<String, dynamic> eventRegistry = jsonDecode(r'''{
  "analytics_consent": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "landing_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "invite_link_open": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "download_click": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "store_page_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "installer_started": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "install_completed": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "first_launch": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_provider_selected": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "signin_succeeded": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "sessionId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": true
  },
  "signin_failed": {
    "properties": {
      "provider": {
        "enum": [
          "email",
          "google",
          "microsoft"
        ]
      },
      "reason": {
        "enum": [
          "cancelled",
          "network",
          "provider",
          "invalid_token",
          "configuration",
          "unknown"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "sessionId": {
        "type": "uuid"
      }
    },
    "observable": true,
    "legacy": false
  },
  "aspiration_selected": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "recipe_created": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "templateCategory": {
        "enum": [
          "calm",
          "focus",
          "health",
          "learning",
          "connection"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "celebration_practiced": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "first_checkin": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "result": {
        "enum": [
          "did",
          "didMore",
          "notToday",
          "undo"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "checkin": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "result": {
        "enum": [
          "did",
          "didMore",
          "notToday",
          "undo"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "comeback": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "recipe_doctor_applied": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "automaticity_score": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "reflection": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "weekly_reflection": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "habit_graduated": {
    "properties": {
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "score": {
        "type": "number",
        "min": 1,
        "max": 7
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "share_initiated": {
    "properties": {
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "invite_accepted": {
    "properties": {
      "channel": {
        "enum": [
          "website",
          "invite",
          "store",
          "direct",
          "unknown",
          "link",
          "email"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "buddy_added": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "paywall_view": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "trial_start": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "purchase": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  },
  "feedback_submitted": {
    "properties": {
      "feedbackId": {
        "type": "uuid"
      },
      "kind": {
        "enum": [
          "Idea",
          "Bug",
          "Question",
          "Praise",
          "This felt wrong",
          "Rating"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "rating_prompted": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": true
  },
  "rating_prompt_shown": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "rated": {
    "properties": {
      "rating": {
        "type": "integer",
        "min": 1,
        "max": 5
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "review_responded": {
    "properties": {
      "feedbackId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "reminder_sent": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": true
  },
  "notif_sent": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "habitId": {
        "type": "uuid"
      },
      "localDay": {
        "type": "date"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_delivered": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_opened": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_actioned": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "action": {
        "enum": [
          "did",
          "snooze",
          "fewer",
          "off",
          "open"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_dismissed": {
    "properties": {
      "notificationId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "notif_disabled": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "localDay": {
        "type": "date"
      }
    },
    "observable": true,
    "legacy": false
  },
  "session_started": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "crash": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "app_hang": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      }
    },
    "observable": true,
    "legacy": false
  },
  "cold_start": {
    "properties": {
      "sessionId": {
        "type": "uuid"
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "latencyMs": {
        "type": "number",
        "min": 0,
        "max": 86400000
      }
    },
    "observable": true,
    "legacy": false
  },
  "sync_error": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "auth_error": {
    "properties": {
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      },
      "errorKind": {
        "enum": [
          "network",
          "authentication",
          "conflict",
          "quota",
          "validation",
          "unavailable",
          "unknown"
        ]
      }
    },
    "observable": true,
    "legacy": false
  },
  "experiment_exposure": {
    "properties": {
      "experiment": {
        "enum": [
          "reminder_copy_v1"
        ]
      },
      "variant": {
        "enum": [
          "control",
          "gentle"
        ]
      },
      "platform": {
        "enum": [
          "windows",
          "macos",
          "linux",
          "android",
          "ios",
          "web"
        ]
      }
    },
    "observable": false,
    "legacy": false
  }
}''') as Map<String, dynamic>;

bool isValidEventProperties(String name, Map<String, Object?> properties) {
  final entry = eventRegistry[name];
  if (entry == null) return false;
  final rules = entry['properties'] as Map<String, dynamic>;
  for (final property in properties.entries) {
    final rule = rules[property.key];
    final value = property.value;
    if (rule == null) return false;
    if (rule['enum'] != null) {
      if (value is! String || !(rule['enum'] as List).contains(value)) return false;
    } else if (rule['type'] == 'uuid') {
      if (value is! String || !RegExp(r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$').hasMatch(value)) return false;
    } else if (rule['type'] == 'date') {
      if (value is! String || !RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(value)) return false;
      final date = DateTime.tryParse('${value}T00:00:00Z');
      if (date == null || date.toIso8601String().substring(0, 10) != value) return false;
    } else {
      if (value is! num || !value.isFinite || value < (rule['min'] as num) || value > (rule['max'] as num)) return false;
      if (rule['type'] == 'integer' && value != value.truncateToDouble()) return false;
    }
  }
  return true;
}
